# Generated by Django 5.2.11 on 2026-03-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="category",
            name="name_kk",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
