# Generated by Django 5.2.11 on 2026-03-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian"), ("kk", "Kazakh")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
    ]
